### PR TITLE
Contribution for IP routing

### PR DESCRIPTION
**Pull request by tony1athome**

### CODE REVIEW

**Review by marcblanchet — CHANGES_REQUESTED** [review]
- rephrasing needed (can be twice): "Mechanisms such as <xref target="ecn"/> can be used to signal storage congestion can be used to request that end nodes throttle their transmissions. "
- don't know the necessity of the "tutorial" on EGP-IGP... are we really thinking people don't know this?
- I see you deleted the static routing portion. Should not that be said?
- I disagree on the addressing proposal: While it could be good to have a unique prefix per celestial body, it may just be too difficult to achieve given various parties, different timelines, politics, ... Moreover, single RIR or a "Space IR" (which has been discussed in another venue) may not fly. Given the limited number of domains per celestial body, in fact, it should not be a lot of prefixes to route.
- should we really discuss about optimal routing is a research topic? I would prefer to be silent and punt this to some research group. That document should be more about: here is what one can do "today" that "works".

**Comment by tony1athome** [comment]
> * rephrasing needed (can be twice): "Mechanisms such as  can be used to signal storage congestion can be used to request that end nodes throttle their transmissions. "

Fixed.

> * don't know the necessity of the "tutorial" on EGP-IGP... are we really thinking people don't know this?

They don't seem to.

> * I see you deleted the static routing portion. Should not that be said?

Well, in fact, the PCE approach is far more accurate.  No one is suggesting unmanaged static routes. So PCE is a far more accurate description.

> * I disagree on the addressing proposal: While it could be good to have a unique prefix per celestial body, it may just be too difficult to achieve given various parties, different timelines, politics, ... Moreover, single RIR or a "Space IR" (which has been discussed in another venue) may not fly. Given the limited number of domains per celestial body, in fact, it should not be a lot of prefixes to route.

I'm hearing politics, not engineering. The single RIR is a necessity: we do not have an official allocation assigned today.  All of the allocations that people are in fact using today are outside of the stated Internet architecture (i.e., not authorized).  We need one RIR.  Note that this is too small a problem for adding another RIR, but it should be possible to just add this to the responsibilities of an existing RIR.  No, it's not likely to be a ton of prefixes, but it would be stupid not to aggregate where possible.

You've written that bandwidth is scarce: why waste it?

> * should we really discuss about optimal routing is a research topic? I would prefer to be silent and punt this to some research group. That document should be more about: here is what one can do "today" that "works".

A better way to silence people is to explicitly say that something is out of scope.  I'll add that.

**Comment by marcblanchet** [comment]
> > * I disagree on the addressing proposal: While it could be good to have a unique prefix per celestial body, it may just be too difficult to achieve given various parties, different timelines, politics, ... Moreover, single RIR or a "Space IR" (which has been discussed in another venue) may not fly. Given the limited number of domains per celestial body, in fact, it should not be a lot of prefixes to route.
> 
> I'm hearing politics, not engineering. The single RIR is a necessity: we do not have an official allocation assigned today. All of the allocations that people are in fact using today are outside of the stated Internet architecture (i.e., not authorized). We need one RIR. Note that this is too small a problem for adding another RIR, but it should be possible to just add this to the responsibilities of an existing RIR. No, it's not likely to be a ton of prefixes, but it would be stupid not to aggregate where possible.

Sure. But I had a call with the RIR CEOs and Vint Cerf on this exact topic. The CEOs said point blank that there is no issue with the current allocation policies to allocate prefixes for space and they already started to do so. 

I could agree with something generic like "better to have aggregation" (without entering into single prefix/RIR discussion) but then I'm not sure it will add much value.

Or I suggest we punt this for now (I also punt many topics from the re-assessment document, such as mandatory IPv6... ;-). 
How about putting this  topic as an on-going issue in the git that we shall tackle later? I better have less contention on the document to start with, especially for things that are a bit out of our control (like starting a new RIR!).

> 
> > * should we really discuss about optimal routing is a research topic? I would prefer to be silent and punt this to some research group. That document should be more about: here is what one can do "today" that "works".
> 
> A better way to silence people is to explicitly say that something is out of scope. I'll add that.

out of scope (instead of being a research topic) I like it better.

**Comment by marcblanchet** [comment]
> 
> > * don't know the necessity of the "tutorial" on EGP-IGP... are we really thinking people don't know this?
> 
> They don't seem to.

I know what/who you are talking about. However, I think we pass that stage of "tutorials" for the "beginners".  I think we should write as if we were targeting our (IETF) community: therefore, some info about deep space specifics, but not much about the "basics of IP".

**Comment by marcblanchet** [comment]
suggesting to further cut text to: "Optimal routing for domains with intermittent links is out of scope of this document."

**Comment by tony1athome** [comment]
> Sure. But I had a call with the RIR CEOs and Vint Cerf on this exact topic. The CEOs said point blank that there is no issue with the current allocation policies to allocate prefixes for space and they already started to do so.
> 

They have no leg to stand on.  Show me where in the documents that that is authorized.

You’ll find that there isn’t anything.

> I could agree with something generic like "better to have aggregation" (without entering into single prefix/RIR discussion) but then I'm not sure it will add much value.
> 
> Or I suggest we punt this for now (I also punt many topics from the re-assessment document, such as mandatory IPv6... ;-).
> How about putting this topic as an on-going issue in the git that we shall tackle later? I better have less contention on the document to start with, especially for things that are a bit out of our control (like starting a new RIR!).
> 

I am not willing to punt this.  This is an important issue for correct operation of the routing architecture.

This should NOT be a big deal: we appoint one RIR, allocate a block, and then use it.

Tony

**Comment by marcblanchet** [comment]
> Sure. But I had a call with the RIR CEOs and Vint Cerf on this exact topic. The CEOs said point blank that there is no issue with the current allocation policies to allocate prefixes for space and they already started to do so.
> They have no leg to stand on. Show me where in the documents that that is authorized. You’ll find that there isn’t anything.

we had a long discussion on that... And that is the whole point I'm trying to get to. 

> I could agree with something generic like "better to have aggregation" (without entering into single prefix/RIR discussion) but then I'm not sure it will add much value. Or I suggest we punt this for now (I also punt many topics from the re-assessment document, such as mandatory IPv6... ;-). How about putting this topic as an on-going issue in the git that we shall tackle later? I better have less contention on the document to start with, especially for things that are a bit out of our control (like starting a new RIR!).
> I am not willing to punt this. This is an important issue for correct operation of the routing architecture. This should NOT be a big deal: we appoint one RIR, allocate a block, and then use it. Tony

It just enters a can of worms into the politics. I've been working pretty hard for quite some time on this project, and I would highly prefer to avoid (or having the least amount) politics at this moment. It has been a pretty hard journey. I would highly prefer that we put this as an issue for later, than having it in the document now. Or some text that does not open the can of worms (aka not mentioning RIRs and single prefix per body).

**Comment by tony1athome** [comment]
Well, then I’m afraid it’s time for us to part company.

Please remove my name from the document.

Tony

**Comment by marcblanchet** [comment]
well, I don't want to loose you for a single small disagreement on how to introduce topics, while on the engineering side, there is agreement.  That would be pretty sad.  I suggest we keep your text and see how it goes. Hopefully, I will be wrong. Please merge so we can move.

**Pull request merged**
